fix: ensure that we only use ipv4 addresses
Spksh/TentacleSoftware.Telnet pull request #7
Opened 2024-07-19 14:59 UTC by victornor

If the first host address is ipv6, bytes length will no longer be 4 and the array copy will throw.

2024-07-19 22:37 UTC, Spksh requested changes
Thanks for the PR!

2024-07-19 22:37 UTC, Spksh commented on TentacleSoftware.Telnet/TelnetClient.cs
> +            byte[] hostAddress = Dns.GetHostAddresses(_host).First(addr => addr.GetAddressBytes().Length == 4).GetAddressBytes();
Would `a => a.AddressFamily == AddressFamily.InterNetwork` work as the selector?

2024-07-19 22:46 UTC, victornor reviewed
Yeah, that's better!
Thanks for the library, it's great.

2024-07-19 22:48 UTC, Spksh approved these changes

2024-07-19 22:48 UTC, merged

2024-07-20 02:22 UTC, Spksh commented
@victornor Published to nuget as pre-release https://www.nuget.org/packages/TentacleSoftware.Telnet/2.2.0-rc1.